global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["seo-node-exporter:9100"]
        labels:
          instance: "seo-engineering-server"

  - job_name: "mongodb"
    static_configs:
      - targets: ["seo-mongodb:27017"]
        labels:
          instance: "mongodb"

  - job_name: "nginx"
    static_configs:
      - targets: ["seo-nginx:80"]
        labels:
          instance: "nginx"

  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["seo-api:3001"]
        labels:
          instance: "api"
