global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['seo-node-exporter:9100']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['seo-api:3001']

  - job_name: 'nginx'
    static_configs:
      - targets: ['seo-nginx:80']
    metrics_path: /nginx_status
