name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install API dependencies
      run: npm ci
      working-directory: api

    - name: Install Website dependencies
      run: npm ci
      working-directory: website

    - name: Install Automation dependencies
      run: npm ci
      working-directory: automation

    - name: Build Website
      run: npm run build
      working-directory: website

    - name: Run Automation Tests
      run: npm test
      working-directory: automation
